#!/usr/bin/env bash
# generate-system-facts.sh — snapshot workstation hardware/OS facts into
# ~/MWM-AI/memory/global/system-facts.md so the OsO responder (Groq + Ollama)
# can answer "what CPU does this device have", "how much RAM", etc.
#
# The output file is markdown picked up by the responder's keyword RAG via
# CONTEXT_DIRS (the existing 48h memory rsync to VPS handles distribution —
# no separate push needed).
#
# Scheduled by oso-system-facts.timer (weekly). Safe to run ad-hoc.
#
# Excludes machine-id, boot-id, MAC addresses, and IPs to keep the file
# clean for the markdown-only memory rsync.

set -euo pipefail

OUT="${OUT:-${HOME}/MWM-AI/memory/global/system-facts.md}"
TS="$(date -u +%Y-%m-%dT%H:%M:%SZ)"

mkdir -p "$(dirname "$OUT")"

# Helpers — all read-only, fail-soft.
field() { awk -F: -v k="$1" 'tolower($1) ~ tolower(k) { sub(/^[ \t]+/, "", $2); print $2; exit }'; }

cpu_model=$(lscpu | field "model name")
cpu_sockets=$(lscpu | field "^socket")
cpu_cores=$(lscpu | field "core\(s\) per socket")
cpu_threads_per_core=$(lscpu | field "thread\(s\) per core")
cpu_logical=$(lscpu | field "^cpu\(s\)")
cpu_max_mhz=$(lscpu | field "cpu max mhz")
cpu_arch=$(lscpu | field "architecture")

mem_total=$(free -h | awk '/^Mem:/ {print $2}')
mem_avail=$(free -h | awk '/^Mem:/ {print $7}')
swap_total=$(free -h | awk '/^Swap:/ {print $2}')

gpu_lines=$(lspci | grep -iE "vga|3d controller|display controller" || true)
nvidia=""
if command -v nvidia-smi >/dev/null 2>&1; then
  nvidia=$(nvidia-smi --query-gpu=name,memory.total,driver_version --format=csv,noheader 2>/dev/null || true)
fi

os_pretty=$(hostnamectl 2>/dev/null | awk -F: '/Operating System/ {sub(/^[ \t]+/, "", $2); print $2}')
kernel=$(uname -srm)
hw_vendor=$(hostnamectl 2>/dev/null | awk -F: '/Hardware Vendor/ {sub(/^[ \t]+/, "", $2); print $2}')
hw_model=$(hostnamectl 2>/dev/null | awk -F: '/Hardware Model/ {sub(/^[ \t]+/, "", $2); print $2}')
chassis=$(hostnamectl 2>/dev/null | awk -F: '/Chassis/ {sub(/^[ \t]+/, "", $2); print $2}' | sed 's/[^a-zA-Z0-9 _-]//g' | awk '{$1=$1};1')
hostname=$(hostname)

# Disk: root + biggest mounted volumes
disk_root=$(df -h / | awk 'NR==2 {print $2 " total, " $4 " free (" $5 " used)"}')

# Pop-shell / DE detection (informational)
de="${XDG_CURRENT_DESKTOP:-unknown}"
session="${XDG_SESSION_TYPE:-unknown}"

# Workspace footprint — count, not paths-with-secrets
projects_count=$(find "${HOME}/MWM-AI/projects" -maxdepth 1 -mindepth 1 -type d 2>/dev/null | wc -l)
memory_count=$(find "${HOME}/MWM-AI/memory" -type f -name '*.md' 2>/dev/null | wc -l)

# Docker services (names only, not exposed ports)
docker_services=""
if command -v docker >/dev/null 2>&1; then
  docker_services=$(docker ps --format '{{.Names}}' 2>/dev/null | sort | tr '\n' ' ' || true)
fi

# Top user systemd timers (names only — gives the model a sense of automation)
user_timers=""
if command -v systemctl >/dev/null 2>&1; then
  user_timers=$(systemctl --user list-timers --no-pager --all 2>/dev/null \
    | grep -oE '[A-Za-z0-9._@-]+\.timer' \
    | sort -u | head -30 | tr '\n' ' ' || true)
fi

{
  cat <<EOF
---
name: workstation system facts
description: Auto-generated hardware/OS snapshot of the primary dev workstation; used by the OsO responder to answer device/spec questions
type: reference
---

# Workstation System Facts

Auto-generated by \`oso-system-facts.timer\` (weekly). Do not edit by hand —
changes will be overwritten. Source: \`projects/oso-sync/deploy/generate-system-facts.sh\`.

Last refresh: ${TS}

## Identity

- Hostname: ${hostname}
- Hardware: ${hw_vendor:-unknown} ${hw_model:-unknown} (${chassis:-unknown})
- OS: ${os_pretty:-unknown}
- Kernel: ${kernel}
- Desktop: ${de} (${session})

## CPU

- Model: ${cpu_model:-unknown}
- Architecture: ${cpu_arch:-unknown}
- Sockets: ${cpu_sockets:-1}
- Cores per socket: ${cpu_cores:-?}
- Threads per core: ${cpu_threads_per_core:-?}
- Logical CPUs: ${cpu_logical:-?}
- Max frequency: ${cpu_max_mhz:-?} MHz

## Memory

- RAM total: ${mem_total:-?}
- RAM available now: ${mem_avail:-?}
- Swap total: ${swap_total:-?}

## GPU

EOF
  if [[ -n "$nvidia" ]]; then
    echo "- NVIDIA: ${nvidia}"
  fi
  if [[ -n "$gpu_lines" ]]; then
    echo "$gpu_lines" | sed 's/^/- /'
  else
    echo "- (none detected)"
  fi

  cat <<EOF

## Storage

- Root filesystem: ${disk_root}

## Workspace footprint

- Projects under \`~/MWM-AI/projects/\`: ${projects_count}
- Memory markdown files under \`~/MWM-AI/memory/\`: ${memory_count}

## Active runtime context

EOF
  if [[ -n "${docker_services// }" ]]; then
    echo "- Running Docker containers: ${docker_services}"
  else
    echo "- Running Docker containers: (none / docker unavailable)"
  fi
  if [[ -n "${user_timers// }" ]]; then
    echo "- User systemd timers: ${user_timers}"
  fi
} > "$OUT"

echo "wrote ${OUT}"
